## Introduction to numpy
- initiation of numpy array
- numpy calculations
- n-dimensional numpy array
- **broadcasting**
- indexing

In [1]:
import numpy as np

In [9]:
x = np.array([1, 2, 3])
type(x)

numpy.ndarray

In [13]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x+y)
print(x*y)
print(x/y)
print(y%x)
print(y//x)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 0]
[4 2 2]


In [6]:
z = np.array([[1, 2], [3, 4]])
z.shape
z.type

(2, 2)
int32


**Broadcasting** enables B to act like (2, 2) when being multiplied to A.

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A*B

array([[10, 40],
       [30, 80]])